name: 'build-docusaurus-docs'
description: 'Create docs using docusaurus'
inputs:
  pre:
    description: 'Install prerelease nbdev/execnb from master?'
    required: false
    default: ''
  version:
    description: 'Version of python to set up'
    required: false
    default: '3.10'
  ghtoken:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Install nbdev-mkdocs Dependencies
      env:
        USE_PRE: ${{ inputs.pre }}
      shell: bash
      run: |
        set -ux
        python -m pip install --upgrade pip
        if [ $USE_PRE ]; then
          pip install -Uq git+https://github.com/fastai/ghapi.git
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -Uq git+https://github.com/fastai/nbdev.git
          wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
          sudo dpkg -i quarto*.deb
        else
          pip install -Uq nbdev
          nbdev_install_quarto
        fi
        test -f setup.py && pip install -e ".[dev]"
    - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
    - name: Install docusaurus dependencies
      run: ./docusaurus/scripts/install_docusaurus_deps.sh
    - name: Build docusaurus docs
      shell: bash
      run: ./docusaurus/scripts/build_docusaurus_docs.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.ghtoken }}
        force_orphan: true
        publish_dir: ./docusaurus/build
        # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
