name: 'build-docs'
description: 'Create docs with nbdev'
inputs:
  pre:
    description: 'Install prerelease nbdev/execnb from master?'
    required: false
    default: ''
  version:
    description: 'Version of python to set up'
    required: false
    default: '3.9'
  ghtoken:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
  doc_deployment_version:
    description: 'The documentation version to be deployed'
    required: false
    default: ''
  doc_deployment_tag:
    description: 'The alias for tagging the new version of the documentation'
    required: false
    default: 'latest'
  default_doc_tag:
    description: "The documentation's default version to redirect the users on page load"
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Install Dependencies
      env:
        USE_PRE: ${{ inputs.pre }}
      shell: bash
      run: |
        set -ux
        python -m pip install --upgrade pip
        if [ $USE_PRE ]; then
          pip install -Uq git+https://github.com/fastai/ghapi.git
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -Uq git+https://github.com/fastai/nbdev.git
          wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
          sudo dpkg -i quarto*.deb
        else
          pip install -Uq nbdev
          nbdev_install_quarto
        fi
        test -f setup.py && pip install -e ".[dev]"
    - name: Build docs
      shell: bash
      run: |
        nbdev_docs
        nbdev_mkdocs docs
    - name: Deploy to GitHub Pages
      if: ${{ inputs.doc_deployment_version == ''}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.ghtoken }}
        force_orphan: true
        publish_dir: ./mkdocs/site
        # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
    - name: Deploy to GitHub Pages using mike
      if: ${{ inputs.doc_deployment_version != ''}}
      shell: bash
      run: |
        git fetch origin gh-pages --depth=1
        git config user.name github-bot
        git config user.email github-bot@@users.noreply.github.com
        mike deploy --config-file mkdocs/mkdocs.yml --update-aliases ${{ inputs.doc_deployment_version }} ${{ inputs.doc_deployment_tag }}
        mike set-default --push --config-file mkdocs/mkdocs.yml ${{ inputs.default_doc_tag }}
